from app.models import db, QuestionStats


def seed_question_stats():
  demo_question_stats = QuestionStats(response_count=15, average=5, question_id=1)
  demo_question_stats_2 = QuestionStats(response_count=15, average=5.6, question_id=2)
  demo_question_stats_3 = QuestionStats(response_count=15, average=5.5, question_id=3)

  demo_question_stats_4 = QuestionStats(response_count=23, average=4.51, question_id=4)
  demo_question_stats_5 = QuestionStats(response_count=23, average=5.35, question_id=5)
  demo_question_stats_6 = QuestionStats(response_count=23, average=5.76, question_id=6)

  demo_question_stats_7 = QuestionStats(response_count=10, average=5.52, question_id=7)
  demo_question_stats_8 = QuestionStats(response_count=10, average=5.51, question_id=8)
  demo_question_stats_9 = QuestionStats(response_count=10, average=5.57, question_id=9)

  demo_question_stats_10 = QuestionStats(response_count=47, average=5.3, question_id=10)
  demo_question_stats_11 = QuestionStats(response_count=47, average=5.2, question_id=11)
  demo_question_stats_12 = QuestionStats(response_count=47, average=4.6, question_id=12)

  demo_question_stats_13 = QuestionStats(response_count=28, average=5.0, question_id=13)
  demo_question_stats_14 = QuestionStats(response_count=28, average=5.0, question_id=14)
  demo_question_stats_15 = QuestionStats(response_count=28, average=5.0, question_id=15)

  demo_question_stats_16 = QuestionStats(response_count=53, average=5.34, question_id=16)
  demo_question_stats_17 = QuestionStats(response_count=53, average=5.41, question_id=17)
  demo_question_stats_18 = QuestionStats(response_count=53, average=5.28, question_id=18)

  demo_question_stats_19 = QuestionStats(response_count=30, average=5.36, question_id=19)
  demo_question_stats_20 = QuestionStats(response_count=30, average=5.81, question_id=20)
  demo_question_stats_21 = QuestionStats(response_count=30, average=5.74, question_id=21)

  demo_question_stats_22 = QuestionStats(response_count=74, average=5.3, question_id=22)
  demo_question_stats_23 = QuestionStats(response_count=74, average=5.3, question_id=23)
  demo_question_stats_24 = QuestionStats(response_count=74, average=5.3, question_id=24)

  demo_question_stats_25 = QuestionStats(response_count=41, average=5.2, question_id=25)
  demo_question_stats_26 = QuestionStats(response_count=41, average=5.2, question_id=26)
  demo_question_stats_27 = QuestionStats(response_count=41, average=5.2, question_id=27)

  demo_question_stats_28 = QuestionStats(response_count=5, average=5.23, question_id=28)
  demo_question_stats_29 = QuestionStats(response_count=5, average=5.7, question_id=29)
  demo_question_stats_30 = QuestionStats(response_count=5, average=5.48, question_id=30)

  demo_question_stats_31 = QuestionStats(response_count=103, average=5.3, question_id=31)
  demo_question_stats_32 = QuestionStats(response_count=103, average=5.3, question_id=32)
  demo_question_stats_33 = QuestionStats(response_count=103, average=5.3, question_id=33)

  demo_question_stats_34 = QuestionStats(response_count=12, average=5.2, question_id=34)
  demo_question_stats_35 = QuestionStats(response_count=12, average=5.2, question_id=35)
  demo_question_stats_36 = QuestionStats(response_count=12, average=5.2, question_id=36)

  demo_question_stats_37 = QuestionStats(response_count=81, average=5.8, question_id=37)
  demo_question_stats_38 = QuestionStats(response_count=81, average=5.8, question_id=38)
  demo_question_stats_39 = QuestionStats(response_count=81, average=5.8, question_id=39)

  demo_question_stats_40 = QuestionStats(response_count=40, average=5.1, question_id=40)
  demo_question_stats_41 = QuestionStats(response_count=40, average=5.1, question_id=41)
  demo_question_stats_42 = QuestionStats(response_count=40, average=5.1, question_id=42)

  demo_question_stats_43 = QuestionStats(response_count=45, average=5.4, question_id=43)
  demo_question_stats_44 = QuestionStats(response_count=45, average=5.4, question_id=44)
  demo_question_stats_45 = QuestionStats(response_count=45, average=5.4, question_id=45)

  demo_question_stats_46 = QuestionStats(response_count=95, average=5.67, question_id=46)
  demo_question_stats_47 = QuestionStats(response_count=95, average=5.67, question_id=47)
  demo_question_stats_48 = QuestionStats(response_count=95, average=5.67, question_id=48)

  demo_question_stats_49 = QuestionStats(response_count=101, average=5.71, question_id=49)
  demo_question_stats_50 = QuestionStats(response_count=101, average=5.71, question_id=50)
  demo_question_stats_51 = QuestionStats(response_count=101, average=5.71, question_id=51)

  demo_question_stats_52 = QuestionStats(response_count=18, average=5.23, question_id=52)
  demo_question_stats_53 = QuestionStats(response_count=18, average=5.23, question_id=53)
  demo_question_stats_54 = QuestionStats(response_count=18, average=5.23, question_id=54)

  demo_question_stats_55 = QuestionStats(response_count=57, average=5.86, question_id=55)
  demo_question_stats_56 = QuestionStats(response_count=57, average=5.86, question_id=56)
  demo_question_stats_57 = QuestionStats(response_count=57, average=5.86, question_id=57)

  demo_question_stats_58 = QuestionStats(response_count=120, average=5.35, question_id=58)
  demo_question_stats_59 = QuestionStats(response_count=120, average=5.35, question_id=59)
  demo_question_stats_60 = QuestionStats(response_count=120, average=5.35, question_id=60)

  demo_question_stats_61 = QuestionStats(response_count=146, average=6.1, question_id=61)
  demo_question_stats_62 = QuestionStats(response_count=146, average=6.1, question_id=62)
  demo_question_stats_63 = QuestionStats(response_count=146, average=6.1, question_id=63)

  demo_question_stats_64 = QuestionStats(response_count=39, average=5.1, question_id=64)
  demo_question_stats_65 = QuestionStats(response_count=39, average=5.1, question_id=65)
  demo_question_stats_66 = QuestionStats(response_count=39, average=5.1, question_id=66)

  demo_question_stats_67 = QuestionStats(response_count=199, average=5.23, question_id=67)
  demo_question_stats_68 = QuestionStats(response_count=199, average=5.23, question_id=68)
  demo_question_stats_69 = QuestionStats(response_count=199, average=5.23, question_id=69)

  demo_question_stats_70 = QuestionStats(response_count=28, average=5.54, question_id=70)
  demo_question_stats_71 = QuestionStats(response_count=28, average=5.54, question_id=71)
  demo_question_stats_72 = QuestionStats(response_count=28, average=5.54, question_id=72)

  demo_question_stats_73 = QuestionStats(response_count=53, average=5.91, question_id=73)
  demo_question_stats_74 = QuestionStats(response_count=53, average=5.91, question_id=74)
  demo_question_stats_75 = QuestionStats(response_count=53, average=5.91, question_id=75)



  db.session.add(demo_question_stats)
  db.session.add(demo_question_stats_2)
  db.session.add(demo_question_stats_3)
  db.session.add(demo_question_stats_4)
  db.session.add(demo_question_stats_5)
  db.session.add(demo_question_stats_6)
  db.session.add(demo_question_stats_7)
  db.session.add(demo_question_stats_8)
  db.session.add(demo_question_stats_9)
  db.session.add(demo_question_stats_10)
  db.session.add(demo_question_stats_11)
  db.session.add(demo_question_stats_12)
  db.session.add(demo_question_stats_13)
  db.session.add(demo_question_stats_14)
  db.session.add(demo_question_stats_15)
  db.session.add(demo_question_stats_16)
  db.session.add(demo_question_stats_17)
  db.session.add(demo_question_stats_18)
  db.session.add(demo_question_stats_19)
  db.session.add(demo_question_stats_20)
  db.session.add(demo_question_stats_21)
  db.session.add(demo_question_stats_22)
  db.session.add(demo_question_stats_23)
  db.session.add(demo_question_stats_24)
  db.session.add(demo_question_stats_25)
  db.session.add(demo_question_stats_26)
  db.session.add(demo_question_stats_27)
  db.session.add(demo_question_stats_28)
  db.session.add(demo_question_stats_29)
  db.session.add(demo_question_stats_30)
  db.session.add(demo_question_stats_31)
  db.session.add(demo_question_stats_32)
  db.session.add(demo_question_stats_33)
  db.session.add(demo_question_stats_34)
  db.session.add(demo_question_stats_35)
  db.session.add(demo_question_stats_36)
  db.session.add(demo_question_stats_37)
  db.session.add(demo_question_stats_38)
  db.session.add(demo_question_stats_39)
  db.session.add(demo_question_stats_40)
  db.session.add(demo_question_stats_41)
  db.session.add(demo_question_stats_42)
  db.session.add(demo_question_stats_43)
  db.session.add(demo_question_stats_44)
  db.session.add(demo_question_stats_45)
  db.session.add(demo_question_stats_46)
  db.session.add(demo_question_stats_47)
  db.session.add(demo_question_stats_48)
  db.session.add(demo_question_stats_49)
  db.session.add(demo_question_stats_50)
  db.session.add(demo_question_stats_51)
  db.session.add(demo_question_stats_52)
  db.session.add(demo_question_stats_53)
  db.session.add(demo_question_stats_54)
  db.session.add(demo_question_stats_55)
  db.session.add(demo_question_stats_56)
  db.session.add(demo_question_stats_57)
  db.session.add(demo_question_stats_58)
  db.session.add(demo_question_stats_59)
  db.session.add(demo_question_stats_60)
  db.session.add(demo_question_stats_61)
  db.session.add(demo_question_stats_62)
  db.session.add(demo_question_stats_63)
  db.session.add(demo_question_stats_64)
  db.session.add(demo_question_stats_65)
  db.session.add(demo_question_stats_66)
  db.session.add(demo_question_stats_67)
  db.session.add(demo_question_stats_68)
  db.session.add(demo_question_stats_69)
  db.session.add(demo_question_stats_70)
  db.session.add(demo_question_stats_71)
  db.session.add(demo_question_stats_72)
  db.session.add(demo_question_stats_73)
  db.session.add(demo_question_stats_74)
  db.session.add(demo_question_stats_75)
  
  db.session.commit()

def undo_question_stats():
  db.session.execute('TRUNCATE question_stats RESTART IDENTITY CASCADE;')
  db.session.commit()
