from app.models import db, Surveys



def seed_surveys():

  survey_01 = Surveys(name='Icebreaker')
  survey_02 = Surveys(name='Friendship')
  survey_03 = Surveys(name='Privacy')
  survey_04 = Surveys(name='Religion')
  survey_05 = Surveys(name='Planning')
  survey_06 = Surveys(name='Style')
  survey_07 = Surveys(name='Conversation')
  survey_08 = Surveys(name='Fitness')
  survey_09 = Surveys(name='Conflict')
  survey_10 = Surveys(name='Education')
  survey_11 = Surveys(name='Marriage')
  survey_12 = Surveys(name='Leisure')
  survey_13 = Surveys(name='Finances')
  survey_14 = Surveys(name='Food')
  survey_15 = Surveys(name='Music')
  survey_16 = Surveys(name='Emotion')
  survey_17 = Surveys(name='Health')
  survey_18 = Surveys(name='Aspirations')
  survey_19 = Surveys(name='Holidays')
  survey_20 = Surveys(name='Arts')
  survey_21 = Surveys(name='Hobbies')
  survey_22 = Surveys(name='Travel')
  survey_23 = Surveys(name='Pets')
  survey_24 = Surveys(name='Fear')
  survey_25 = Surveys(name='Habits')

  # db.session.add(survey_00)
  db.session.add(survey_01)
  db.session.add(survey_02)
  db.session.add(survey_03)
  db.session.add(survey_04)
  db.session.add(survey_05)
  db.session.add(survey_06)
  db.session.add(survey_07)
  db.session.add(survey_08)
  db.session.add(survey_09)
  db.session.add(survey_10)
  db.session.add(survey_11)
  db.session.add(survey_12)
  db.session.add(survey_13)
  db.session.add(survey_14)
  db.session.add(survey_15)
  db.session.add(survey_16)
  db.session.add(survey_17)
  db.session.add(survey_18)
  db.session.add(survey_19)
  db.session.add(survey_20)
  db.session.add(survey_21)
  db.session.add(survey_22)
  db.session.add(survey_23)
  db.session.add(survey_24)
  db.session.add(survey_25)

  db.session.commit()


def undo_surveys():
  db.session.execute('TRUNCATE surveys RESTART IDENTITY CASCADE;')
  db.session.commit()
