"""Fixed question response table

Revision ID: 7bfbaec0ff70
Revises: 55926aaafe06
Create Date: 2022-02-07 09:10:57.227149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfbaec0ff70'
down_revision = '55926aaafe06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_responses_user_id_key', 'question_responses', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('question_responses_user_id_key', 'question_responses', ['user_id'])
    # ### end Alembic commands ###
